### ISSUE TITLE
Hierarchial Taxonomy support.

### ISSUE THREAD

**Issue by spsinghats** [nkostadinov/yii2-taxonomy#11]
Does this extension support hierarchial taxonomy? Generally a taxonomy vocabulary is nested and hierarchial. Do we plan on having this support?

**Comment by nkostadinov** [comment]
Many taxonomies have a hierarchical structure, but this is not a requirement. But anyway :) this extension provides hierarchical structure via the category taxonomy. The terms are build hierarchically and the data table holds the assignment of each "leaf" to an object. 

If you have any questions regarding the functionality feel free to ask here.
