### ISSUE TITLE
Migration fails with UnknownPropertyExeption

### ISSUE THREAD

**Issue by larry-tx** [nkostadinov/yii2-taxonomy#12]
I installed your extension and made the necessary change to the "components" section of main.php in config. When I try to do the migration, I get the following:
```
yii migrate --migrationPath=@nkostadinov/taxonomy/migrations
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::enableCsrfValidation'

in W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Component.php:201

Stack trace:
#0 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\BaseYii.php(529): yii\base\Component->__set('enableCsrfValid...', true)
#1 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Object.php(105): yii\BaseYii::configure(Object(yii\console\Request), Array)
#2 [internal function]: yii\base\Object->__construct(Array)
#3 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\Container.php(381): ReflectionClass->newInstanceArgs(Array)
#4 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('yii\\console\\Req...', Array, Array)
#5 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\BaseYii.php(348): yii\di\Container->get('yii\\console\\Req...', Array, Array)
#6 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#7 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\Application.php(219): yii\di\ServiceLocator->get('request')
#8 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Application.php(380): yii\console\Application->getRequest()
#9 W:\xampp\htdocs\public_html\yii(27): yii\base\Application->run()
#10 {main}
PHP Warning:  array_map(): An error occurred while invoking the map callback in W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\FileTarget.php on line 106
PHP Stack trace:
PHP   1. yii\base\ErrorHandler->handleException() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\ErrorHandler.php:0
PHP   2. yii\log\Logger->flush() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\ErrorHandler.php:113
PHP   3. yii\log\Dispatcher->dispatch() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\Logger.php:177
PHP   4. yii\log\Target->collect() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\Dispatcher.php:188
PHP   5. yii\log\FileTarget->export() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\Target.php:124
PHP   6. array_map() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\FileTarget.php:106
```

**Comment by nkostadinov** [comment]
Hi Larry,

I just created a new project,added the extension and ran the migration without any problems. May be the problem is in your application. Do you have configuration of "request" component in the console config file trying to set "enableCsrfValidation" ?

**Comment by larry-tx** [comment]
I suspect that the problem is with Yii itself. However, in response to your question:


  1.  There is nothing whatsoever in console/config/main.php, config/main-local.php, or console/config/bootstrap.php regarding CsrfValidation.
  2.  I have made no changes whatsoever to anything in /console since installing Yii2 in the directory via Composer.
  3.  I did a “Find in Path” on the entire /console directory and found nothing whatsoever that matches “csrf.”

Unfortunately, Yii2 provides limited and not very useful error reporting. For what it’s worth, here’s the entire stack trace from the error:

W:\xampp\htdocs\public_html>yii migrate --migrationPath=@nkostadinov/taxonomy/migrations
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::enableCsrfValidation'

in W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Component.php:201

Stack trace:
#0 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\BaseYii.php(529): yii\base\Component->__set('enableCsrfValid...', true)
#1 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Object.php(105): yii\BaseYii::configure(Object(yii\console\Request), Array)
#2 [internal function]: yii\base\Object->__construct(Array)
#3 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\Container.php(381): ReflectionClass->newInstanceArgs(Array)
#4 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('yii\\console\\Req...', Array, Array)
#5 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\BaseYii.php(348): yii\di\Container->get('yii\\console\\Req...', Array, Array)
#6 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#7 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\Application.php(219): yii\di\ServiceLocator->get('request')
#8 W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Application.php(380): yii\console\Application->getRequest()
#9 W:\xampp\htdocs\public_html\yii(27): yii\base\Application->run()
#10 {main}
PHP Warning:  array_map(): An error occurred while invoking the map callback in W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\FileTarget.php on line 106
PHP Stack trace:
PHP   1. yii\base\ErrorHandler->handleException() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\ErrorHandler.php:0
PHP   2. yii\log\Logger->flush() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\ErrorHandler.php:113
PHP   3. yii\log\Dispatcher->dispatch() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\Logger.php:177
PHP   4. yii\log\Target->collect() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\Dispatcher.php:188
PHP   5. yii\log\FileTarget->export() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\Target.php:124
PHP   6. array_map() W:\xampp\htdocs\public_html\vendor\yiisoft\yii2\log\FileTarget.php:106

As you can see, the call to enableCsrfValidation comes in BaseYii.php (yii\base\Component->__set('enableCsrfValid...', true) on line 529. Interestingly, /console/runtime/logs/app.log shows absolutely no errors despite all of the stuff displayed in the console.

I should mention that migrations worked just fine on this installation in the past. I can’t pinpoint precisely when it was, but I strongly suspect a recent update in Yii2. I’ve run “composer update” several times between the last time migrations worked and when this problem arose.

If you have any further ideas on how to chase this down, I’d greatly appreciate them.

Larry

**Comment by nkostadinov** [comment]
I believe you are using the advanced template. Can you check if you have request component configuration  in the common folder ? If you run anything else in the console is it working ?

**Comment by nkostadinov** [comment]
Closing this as the problem is not related to the extension. If you have any other issues I'll be glad to help.
