### ISSUE TITLE
dev/master failed to access taxonomy (HTTP ERROR 500)

### ISSUE THREAD

**Issue by phucnguyenvn** [nkostadinov/yii2-taxonomy#7]
I tried config module and component but not work at all
http://localhost:8080/taxonomy get HTTP ERROR 500
please help me, thank you.

**Comment by nkostadinov** [comment]
Hi, can you show me how you configured the module and component. 

did you run the migrations ?

**Comment by phucnguyenvn** [comment]
HI, thank you for your honest reply,
I'm read the doc and I understanding when I configured the module part:

`'modules' => [
        ......
        'taxonomy' => [
            'class' => 'nkostadinov\taxonomy\Module'
        ],`

I can able to access to the management interface and it will automatically generate the migration. So.. I'm not yet run the migrations.
Let me try and feedback for you, but I think you need to add the migrations step in to your documentation.

**Comment by phucnguyenvn** [comment]
After tried the migrations I still get this error, nothing change.

**Comment by phucnguyenvn** [comment]
This is my config file:

```
<?php

$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'defaultRoute' => 'hosts/index',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log','app\modules\tagmanagement\config\settings'],
    'modules' => [
        'tag-manage' => [
            'class' => 'app\modules\tagmanagement\tag',
        ],
        'taxonomy' => [
            'class' => 'nkostadinov\taxonomy\Module'
        ],
    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'p2f0ZCyusf-uDCvRXxlKSbeas0TVNKSm',
            'parsers' => [
                 'application/json' => 'yii\web\JsonParser',
             ]
        ],
        'taxonomy' => [
            'class' => 'nkostadinov\taxonomy\Taxonomy',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),

        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
              '<action:(home|index|login|logout|about)>'=>'site/<action>',
              // '<controller:\w+>/<id:\d+>'=>'<controller>/view',
              // '<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
              // '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
            ],
        ],
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
    ];
}

return $config;
```

**Comment by nkostadinov** [comment]
If you see the migration interface this means that you have setup the module correctly. When exactly do you see this error ? Can you see what is the exact error in the application log because error 500 is general error.
When you add a new taxonomy via the interface the migration is automatically executed.

**Comment by phucnguyenvn** [comment]
Thank you, I cannot see the migration interface, I get this error when I try to access this interface, and the browser throw only error 500 with the blank page

**Comment by nkostadinov** [comment]
Do you have proper .htaccess file set for pretty url ? Can you try to access it like this: 

http://localhost:8080/index.php?r=taxonomy

**Comment by phucnguyenvn** [comment]
I tried the above also, but it's not work

**Comment by nkostadinov** [comment]
Did you run the initial migration like this (I added that to the readme)
yii migrate --migrationPath=@nkostadinov/taxonomy/migrations

If that doesnt work you need to check your logs and provide some more info about the error. There is no reason to throw error 500. I assume this might not be from the extension.
